#!/usr/bin/perl -W

# the first argument should be the *fullpath* of the folder that contains all
# the files generated by benchGen.
# this script uses LOAD DATA without LOCAL (server process directly accesses the CSV files).
# LOAD DATA without LOCAL is faster, but note that it needs more permissions.
# you should make folder under mysql directory and make it readable by everyone.

$csvpath = shift;
$dbname = shift;
$imagesize = shift;
if ($csvpath eq "" || $dbname eq "" || $imagesize eq "") {
  print "Usage: ./insertToMySQL_general.pl <csvfolder> <dbname> <imagesize>.\n";
  print "Ex: ./insertToMySQL_general.pl /var/lib/mysql/csvs/ mytest1 1000.\n";
  print "The first argument should be the full path of the directory that contains ALL data files, and is under mysql folder. (ex. /var/lib/mysql/tmpfolder, /data/hkimura/db13/tmpcsvs,...). Don't forget to make the folder readable by everyone.\n";
  exit;
}
print "Loading data in $csvpath to $dbname. imagesize=$imagesize..\n";

$path = `pwd`;
chomp($path);
#need to already have entered sudo password once to make this work - presumably when starting mysqld_safe

#create images table
`sudo mysql $dbname -e \"drop table if exists images\"`;
`sudo mysql $dbname -e \"CREATE TABLE images (imageid INT NOT NULL PRIMARY KEY, xstart INT NOT NULL, ystart INT NOT NULL, xend INT NOT NULL, yend INT NOT NULL, time INT NOT NULL, cycle INT NOT NULL, tablename VARCHAR(20) NOT NULL) ENGINE=MyISAM\"`;

`sudo mysql $dbname -e \" LOAD DATA INFILE '$csvpath/bench.pos' INTO TABLE images FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'\"`;
`sudo mysql $dbname -e \"UPDATE images SET xend=xstart+$imagesize,yend=ystart+$imagesize,time=imageid,cycle=floor(imageid/20),tablename=CONCAT('bench_',LPAD(CAST(imageid AS CHAR),4,'0'))\"`;

open FILE, "$csvpath/bench.pos";
@data = <FILE>;
close FILE;

foreach $line (@data)
{
    chomp($line);
    @components = split(/,/, $line);
    $tablename = $components[$#components];
    $abs_path = $csvpath . "/" . $tablename;
    print "Working on $tablename\n";
    `sudo mysql $dbname -e \"drop table if exists $tablename\"`;
    `sudo mysql $dbname -e \"create table $tablename(tile INT NOT NULL, x INT NOT NULL, y INT NOT NULL, pix INT NOT NULL, var INT NOT NULL, valid INT NOT NULL, sat INT NOT NULL, v0 INT NOT NULL, v1 INT NOT NULL, v2 INT NOT NULL, v3 INT NOT NULL, v4 INT NOT NULL, v5 INT NOT NULL, v6 INT NOT NULL, CONSTRAINT PRIMARY KEY Raw_x_PK (tile, y, x)) ENGINE=INNODB\"`;
    # `sudo mysql $dbname -e \"create table $tablename(tile INT NOT NULL, x INT NOT NULL, y INT NOT NULL, pix INT NOT NULL, var INT NOT NULL, valid INT NOT NULL, sat INT NOT NULL, v0 INT NOT NULL, v1 INT NOT NULL, v2 INT NOT NULL, v3 INT NOT NULL, v4 INT NOT NULL, v5 INT NOT NULL, v6 INT NOT NULL, CONSTRAINT PRIMARY KEY Raw_x_PK (tile, y, x)) ENGINE=INNODB ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=4\"`;
    # LOAD DATA without LOCAL is faster, but note that it needs more permissions
    # We ARE sure the primary key value is unique. This will speed up the loading.
    # however we should disable it when we see something weird.
    `sudo mysql $dbname -e \"SET UNIQUE_CHECKS=0; LOAD DATA INFILE '$abs_path' INTO TABLE $tablename FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';SET UNIQUE_CHECKS=1;\"`;
}
